site_name: ETL com Python
theme: 
  name: readthedocs
  palette:
    primary: blue
    accent: blue
    toggle:
      icon: menu
      name: Menu
    language: pt

repo_name: 'vorges-data/workshop01_data_project'
repo_url: 'https://github.com/vorges-data/workshop01_data_project'

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: code-block-caption
          class: caption

plugins:
  - search
  - mkdocstrings:
      default_handler: python
