site_name: Projeto ETL com Python
theme:
  name: material
  palette:
    primary: black
  language: pt

repo_name: 'vorges-data/workshop01_data_project'
repo_url: 'https://github.com/vorges-data/workshop01_data_project'


markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
