[tool.poetry]
name = "workshop01-data-project"
version = "0.1.0"
description = "Projeto de ETL no python"
authors = ["Vinicius Borges"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.3"
openpyxl = "^3.1.2"
pandas = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
